databases:
- name: temporal
  databaseName: temporal
  user: temporal
  plan: standard
- name: temporal-visibility
  databaseName: visibility
  user: visibility
  plan: standard

services:
- type: web
  name: temporal-frontend
  autoDeploy: false
  plan: Standard
  env: docker
  dockerfilePath: ./server-auto-setup/Dockerfile
  envVars:
  - key: FRONTEND_GRPC_PORT # TODO necessary?
    value: 10000
  - key: SERVICES
    value: frontend
  - key: TEMPORAL_CLI_ADDRESS_RENDER_OVERRIDE
    fromService:
      name: temporal-frontend
      type: web
      property: hostport
  - key: DYNAMIC_CONFIG_FILE_PATH
    value: /etc/temporal/dynamicconfig.yaml
  - key: SKIP_POSTGRES_DB_CREATION
    value: true # Render creates the database when the DB is created
  - key: DB
    value: postgresql
  - key: DBNAME
    fromDatabase:
      name: temporal
      property: database
  - key: DB_PORT
    fromDatabase:
      name: temporal
      property: port
  - key: POSTGRES_USER
    fromDatabase:
      name: temporal
      property: user
  - key: POSTGRES_PWD
    fromDatabase:
      name: temporal
      property: password
  - key: POSTGRES_SEEDS
    fromDatabase:
      name: temporal
      property: host
  - key: VISIBILITY_DBNAME
    fromDatabase:
      name: temporal-visibility
      property: database
  - key: VISIBILITY_DB_PORT
    fromDatabase:
      name: temporal-visibility
      property: port
  - key: VISIBILITY_POSTGRES_USER
    fromDatabase:
      name: temporal-visibility
      property: user
  - key: VISIBILITY_POSTGRES_PWD
    fromDatabase:
      name: temporal-visibility
      property: password
  - key: VISIBILITY_POSTGRES_SEEDS
    fromDatabase:
      name: temporal-visibility
      property: host
- type: pserv
  name: temporal-history
  autoDeploy: false
  plan: Standard
  env: docker
  dockerfilePath: ./server/Dockerfile
  envVars:
  - key: SKIP_SCHEMA_SETUP
    value: true
  - key: SERVICES
    value: history
  - key: PUBLIC_FRONTEND_ADDRESS
    fromService:
      name: temporal-frontend
      type: web
      property: hostport
  - key: TEMPORAL_CLI_ADDRESS
    fromService:
      name: temporal-frontend
      type: web
      property: hostport
  - key: DB
    value: postgresql
  - key: DBNAME
    fromDatabase:
      name: temporal
      property: database
  - key: VISIBILITY_DBNAME
    fromDatabase:
      name: temporal
      property: database
  - key: DYNAMIC_CONFIG_FILE_PATH
    value: /etc/temporal/dynamicconfig.yaml
  - key: POSTGRES_USER
    fromDatabase:
      name: temporal
      property: user
  - key: POSTGRES_PWD
    fromDatabase:
      name: temporal
      property: password
  - key: POSTGRES_SEEDS
    fromDatabase:
      name: temporal
      property: host
- type: pserv
  name: temporal-matching
  autoDeploy: false
  plan: Standard
  env: docker
  dockerfilePath: ./server/Dockerfile
  envVars:
    - key: SKIP_SCHEMA_SETUP
      value: true
    - key: SERVICES
      value: matching
    - key: PUBLIC_FRONTEND_ADDRESS
      fromService:
        name: temporal-frontend
        type: web
        property: hostport
    - key: TEMPORAL_CLI_ADDRESS
      fromService:
        name: temporal-frontend
        type: web
        property: hostport
    - key: DB
      value: postgresql
    - key: DBNAME
      fromDatabase:
        name: temporal
        property: database
    - key: VISIBILITY_DBNAME
      fromDatabase:
        name: temporal
        property: database
    - key: DYNAMIC_CONFIG_FILE_PATH
      value: /etc/temporal/dynamicconfig.yaml
    - key: POSTGRES_USER
      fromDatabase:
        name: temporal
        property: user
    - key: POSTGRES_PWD
      fromDatabase:
        name: temporal
        property: password
    - key: POSTGRES_SEEDS
      fromDatabase:
        name: temporal
        property: host
- type: pserv
  autoDeploy: false
  name: temporal-worker
  env: docker
  dockerfilePath: ./server/Dockerfile
  envVars:
    - key: SERVICES
      value: worker
    - key: PUBLIC_FRONTEND_ADDRESS
      fromService:
        name: temporal-frontend
        type: web
        property: hostport
    - key: TEMPORAL_CLI_ADDRESS
      fromService:
        name: temporal-frontend
        type: web
        property: hostport
    - key: DB
      value: postgresql
    - key: DBNAME
      fromDatabase:
        name: temporal
        property: database
    - key: VISIBILITY_DBNAME
      fromDatabase:
        name: temporal
        property: database
    - key: DYNAMIC_CONFIG_FILE_PATH
      value: /etc/temporal/dynamicconfig.yaml
    - key: POSTGRES_USER
      fromDatabase:
        name: temporal
        property: user
    - key: POSTGRES_PWD
      fromDatabase:
        name: temporal
        property: password
    - key: POSTGRES_SEEDS
      fromDatabase:
        name: temporal
        property: host
- type: worker
  name: temporal-admin-tools
  autoDeploy: false
  plan: Standard
  env: docker
  dockerfilePath: ./admin-tools/Dockerfile
  envVars:
  - key: TEMPORAL_CLI_ADDRESS
    fromService:
      name: temporal-frontend
      type: web
      property: hostport
- type: web
  name: temporal-web
  autoDeploy: false
  plan: Standard
  env: docker
  dockerfilePath: ./web/Dockerfile
  envVars:
  - key: PORT
    value: 8088
  - key: TEMPORAL_PERMIT_WRITE_API
    value: true
  - key: TEMPORAL_GRPC_ENDPOINT
    fromService:
      name: temporal-frontend
      type: web
      property: hostport
